.PHONY: setup
setup:
	./scripts/setup.sh

.PHONY: dev
dev:
	npm run dev

.PHONY: lint
lint:
	npm run all

# This output is generated inside the .next folder
.PHONY: build
build:
	npm run build

# .PHONY: deploy
# deploy:
# 	npm run export